# 
# Dependencies ------------------------------------------------------------
# install.packages("sf")
# install.packages("rnaturalearth")
# install.packages("rnaturalearthdata")
# install.packages("rnaturalearthhires")
# install.packages("sjPlot")
# install.packages(c("dplyr", "tidyr", "flextable"))
# install.packages("webshot2")
# webshot2::install_phantomjs()
# install.packages("car")  
# install.packages("sandwich")
# install.packages("lmtest")
library(tidyverse)
library(scales)
library(readxl)
library(haven)
library(foreign)
library(dplyr)
library(survey)
library(broom)
library(here)
library(gtsummary)
library(readr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)
library(gt)
library(sjPlot)
library(stringr)
library(maps)       
library(viridis)
library(patchwork)
library(webshot2)
library(car)
library(sandwich)
library(lmtest)
library(pROC)


